/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ProxySchema = YoutubeAPIProxyResponse;

export interface YoutubeAPIProxyResponse {
  time?: number;
  "youtube-data"?: YoutubeData;
  "youtube-dislike"?: YoutubeDislike;
  "youtube-operational"?: YoutubeOperational;
  "youtube-transcripts"?: YoutubeTranscripts;
}
export interface YoutubeData {
  etag?: string;
  items?: YoutubeDataItem[];
  kind?: string;
  pageInfo?: PageInfo;
}
export interface YoutubeDataItem {
  contentDetails?: ContentDetails;
  etag?: string;
  id?: string;
  kind?: string;
  player?: Player;
  recordingDetails?: Content;
  snippet?: Snippet;
  statistics?: Statistics;
  status?: Status;
}
export interface ContentDetails {
  caption?: string;
  contentRating?: Content;
  definition?: string;
  dimension?: string;
  duration?: string;
  licensedContent?: boolean;
  projection?: string;
}
export interface Content {}
export interface Player {
  embedHtml?: string;
}
export interface Snippet {
  categoryId?: string;
  channelId?: string;
  channelTitle?: string;
  defaultAudioLanguage?: string;
  defaultLanguage?: string;
  description?: string;
  liveBroadcastContent?: string;
  localized?: Localized;
  publishedAt?: string;
  thumbnails?: Thumbnails;
  title?: string;
}
export interface Localized {
  description?: string;
  title?: string;
}
export interface Thumbnails {
  default?: Default;
  high?: Default;
  maxres?: Default;
  medium?: Default;
  standard?: Default;
}
export interface Default {
  height?: number;
  url?: string;
  width?: number;
}
export interface Statistics {
  commentCount?: string;
  favoriteCount?: string;
  likeCount?: string;
  viewCount?: string;
}
export interface Status {
  embeddable?: boolean;
  license?: string;
  madeForKids?: boolean;
  privacyStatus?: string;
  publicStatsViewable?: boolean;
  uploadStatus?: string;
}
export interface PageInfo {
  resultsPerPage?: number;
  totalResults?: number;
}
export interface YoutubeDislike {
  dateCreated?: string;
  deleted?: boolean;
  dislikes?: number;
  id?: string;
  likes?: number;
  rating?: number;
  rawDislikes?: number;
  rawLikes?: number;
  viewCount?: number;
}
export interface YoutubeOperational {
  etag?: string;
  items?: YoutubeOperationalItem[];
  kind?: string;
}
export interface YoutubeOperationalItem {
  chapters?: Chapters;
  etag?: string;
  id?: string;
  kind?: string;
}
export interface Chapters {
  areAutoGenerated?: boolean;
  chapters?: Chapter[];
}
export interface Chapter {
  thumbnails?: Default[];
  time?: number;
  title?: string;
}
export interface YoutubeTranscripts {
  English?: English;
  German?: English;
}
export interface English {
  _url?: string;
  content?: Content;
  is_generated?: boolean;
  is_translatable?: boolean;
  language_code?: string;
  url?: string;
}
