/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HomeSchema = HomeResponse;

export interface HomeResponse {
	readonly data: Datum[];
	readonly links: Links;
	readonly meta: Meta;
	readonly success: boolean;
}
export interface Datum {
	readonly id: number;
	readonly slug: string;
	readonly url_slug: string;
	readonly short_url: string;
	readonly url: string;
	readonly title: string;
	readonly featured: boolean;
	readonly remote: boolean;
	readonly remote_url: null;
	readonly description: string;
	readonly duration: number;
	readonly duration_pretty: string;
	readonly likes_count: number;
	readonly comments_count: number;
	readonly thumbnail: Thumbnail;
	readonly perspectives: Perspective[];
	readonly channels: Channel[];
	readonly publish_date: string;
	readonly preferences: Preferences;
}
export interface Thumbnail {
	readonly id: number;
	readonly collection: string;
	readonly remote_url: null;
	readonly variations: Variation[];
}
export interface Variation {
	readonly height: number;
	readonly file: string;
	readonly url: string;
}
export interface Perspective {
	readonly id: number;
	readonly title: null;
	readonly title_pluralized: string;
	readonly main: boolean;
}
export interface Channel {
	readonly id: number;
	readonly slug: string;
	readonly title: string;
	readonly description: null;
	readonly url_slug: string;
	readonly videos_count: null;
	readonly followings_count: null;
}
export interface Preferences {
	readonly comments: boolean;
	readonly likes: boolean;
	readonly tags: boolean;
	readonly shares: boolean;
	readonly clips: boolean;
}
export interface Links {
	readonly first: string;
	readonly last: string;
	readonly prev: null;
	readonly next: string;
}
export interface Meta {
	readonly current_page: number;
	readonly from: number;
	readonly last_page: number;
	readonly links: Link[];
	readonly path: string;
	readonly per_page: number;
	readonly to: number;
	readonly total: number;
}
export interface Link {
	readonly url: null | string;
	readonly label: string;
	readonly active: boolean;
}
