/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Home = HomeResponse;

export interface HomeResponse {
  data: Datum[];
  links: Links;
  meta: Meta;
  success: boolean;
}
export interface Datum {
  id: number;
  slug: string;
  url_slug: string;
  short_url: string;
  url: string;
  title: string;
  featured: boolean;
  remote: boolean;
  remote_url: null;
  description: string;
  duration: number;
  duration_pretty: string;
  likes_count: number;
  comments_count: number;
  thumbnail: Thumbnail;
  perspectives: Perspective[];
  channels: Channel[];
  publish_date: string;
  preferences: Preferences;
}
export interface Thumbnail {
  id: number;
  collection: string;
  remote_url: null;
  variations: Variation[];
}
export interface Variation {
  height: number;
  file: string;
  url: string;
}
export interface Perspective {
  id: number;
  title: null;
  title_pluralized: string;
  main: boolean;
}
export interface Channel {
  id: number;
  slug: string;
  title: string;
  description: null;
  url_slug: string;
  videos_count: null;
  followings_count: null;
}
export interface Preferences {
  comments: boolean;
  likes: boolean;
  tags: boolean;
  shares: boolean;
  clips: boolean;
}
export interface Links {
  first: string;
  last: string;
  prev: null;
  next: string;
}
export interface Meta {
  current_page: number;
  from: number;
  last_page: number;
  links: Link[];
  path: string;
  per_page: number;
  to: number;
  total: number;
}
export interface Link {
  url: null | string;
  label: string;
  active: boolean;
}
