/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PlaylistSchema = PlaylistResponse;

export interface PlaylistResponse {
	readonly playlist: Playlist;
	readonly success: boolean;
}
export interface Playlist {
	readonly id: number;
	readonly slug: string;
	readonly title: string;
	readonly description: null;
	readonly type: number;
	readonly publish_date: string;
	readonly meta_tags: null;
	readonly url_slug: string;
	readonly videos_count: number;
	readonly followings_count: number;
}
