/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Playlist = PlaylistResponse;

export interface PlaylistResponse {
  playlist: Playlist;
  success: boolean;
}
export interface Playlist {
  id: number;
  slug: string;
  title: string;
  description: null;
  type: number;
  publish_date: string;
  meta_tags: null;
  url_slug: string;
  videos_count: number;
  followings_count: number;
}
