/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SearchSchema = SearchResponse;
export type Collection = "thumbnail";
export type Slug = string;
export type Title = string;
export type URLSlug = string;

export interface SearchResponse {
  data: Datum[];
  links: Links;
  meta: Meta;
  counts: Counts;
  success: boolean;
}
export interface Datum {
  id: number;
  slug: string;
  url_slug: string;
  short_url: string;
  url: string;
  title: string;
  featured: boolean;
  remote: boolean;
  remote_url: null;
  description: null;
  likes_count: null;
  comments_count: null;
  thumbnail: Thumbnail;
  channels: Channel[];
  publish_date: string;
  preferences: Preferences;
}
export interface Thumbnail {
  id: number;
  collection: Collection;
  remote_url: null;
  variations: Variation[];
}
export interface Variation {
  height: number;
  file: string;
  url: string;
}
export interface Channel {
  id: number;
  slug: Slug;
  title: Title;
  description: null;
  url_slug: URLSlug;
  videos_count: null;
  followings_count: null;
}
export interface Preferences {
  comments: boolean;
  likes: boolean;
  tags: boolean;
  shares: boolean;
  clips: boolean;
}
export interface Links {
  first: string;
  last: string;
  prev: null;
  next: string;
}
export interface Meta {
  current_page: number;
  from: number;
  last_page: number;
  links: Link[];
  path: string;
  per_page: number;
  to: number;
  total: number;
}
export interface Link {
  url: null | string;
  label: string;
  active: boolean;
}
export interface Counts {
  videos: number;
  articles: number;
  playlists: number;
  channels: number;
  podcasts: number;
  tags: number;
  suggestions: number;
}
