/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SearchSchema = SearchResponse;
export type Slug = string;
export type Title = string;
export type URLSlug = string;

export interface SearchResponse {
	readonly data: Datum[];
	readonly links: Links;
	readonly meta: Meta;
	readonly counts: Counts;
	readonly success: boolean;
}
export interface Datum {
	readonly id: number;
	readonly slug: string;
	readonly url_slug: string;
	readonly short_url: string;
	readonly url: string;
	readonly title: string;
	readonly featured: boolean;
	readonly remote: boolean;
	readonly remote_url: null;
	readonly description: null;
	readonly likes_count: null;
	readonly comments_count: null;
	readonly thumbnail: Thumbnail;
	readonly channels: Channel[];
	readonly publish_date: string;
	readonly preferences: Preferences;
}
export interface Thumbnail {
	readonly id: number;
	readonly collection: Collection;
	readonly remote_url: null;
	readonly variations: Variation[];
}
export interface Variation {
	readonly height: number;
	readonly file: string;
	readonly url: string;
}
export interface Channel {
	readonly id: number;
	readonly slug: Slug;
	readonly title: Title;
	readonly description: null;
	readonly url_slug: URLSlug;
	readonly videos_count: null;
	readonly followings_count: null;
}
export interface Preferences {
	readonly comments: boolean;
	readonly likes: boolean;
	readonly tags: boolean;
	readonly shares: boolean;
	readonly clips: boolean;
}
export interface Links {
	readonly first: string;
	readonly last: string;
	readonly prev: null;
	readonly next: string;
}
export interface Meta {
	readonly current_page: number;
	readonly from: number;
	readonly last_page: number;
	readonly links: Link[];
	readonly path: string;
	readonly per_page: number;
	readonly to: number;
	readonly total: number;
}
export interface Link {
	readonly url: null | string;
	readonly label: string;
	readonly active: boolean;
}
export interface Counts {
	readonly videos: number;
	readonly articles: number;
	readonly playlists: number;
	readonly channels: number;
	readonly podcasts: number;
	readonly tags: number;
	readonly suggestions: number;
}

export const enum Collection {
	thumbnail = "thumbnail"
}
