/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type VideoDetailsSchema = VideoDetailsResponse;

export interface VideoDetailsResponse {
	readonly video: Video;
	readonly success: boolean;
}
export interface Video {
	readonly id: number;
	readonly slug: string;
	readonly url_slug: string;
	readonly short_url: string;
	readonly url: string;
	readonly title: string;
	readonly featured: boolean;
	readonly remote: boolean;
	readonly remote_url: null;
	readonly description: string;
	readonly duration: number;
	readonly duration_pretty: string;
	readonly likes_count: number;
	readonly comments_count: number;
	readonly thumbnail: Thumbnail;
	readonly perspectives: Perspective[];
	readonly channels: Channel[];
	readonly publish_date: string;
	readonly preferences: Preferences;
}
export interface Thumbnail {
	readonly id: number;
	readonly collection: string;
	readonly remote_url: null;
	readonly variations: Variation[];
}
export interface Variation {
	readonly height: number;
	readonly file: string;
	readonly url: string;
}
export interface Perspective {
	readonly id: number;
	readonly title: null;
	readonly title_pluralized: string;
	readonly main: boolean;
}
export interface Channel {
	readonly id: number;
	readonly slug: string;
	readonly title: string;
	readonly description: null;
	readonly url_slug: string;
	readonly videos_count: null;
	readonly followings_count: null;
}
export interface Preferences {
	readonly comments: boolean;
	readonly likes: boolean;
	readonly tags: boolean;
	readonly shares: boolean;
	readonly clips: boolean;
}
