/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type VideoPlayerSchema = VideoPlayerResponse;

export interface VideoPlayerResponse {
	readonly options: Options;
	readonly advertising: Advertising[];
	readonly success: boolean;
}
export interface Options {
	readonly visual: Visual;
	readonly generic: Generic;
	readonly tracks: Track[];
}
export interface Visual {
	readonly fluid: boolean;
	readonly responsive: boolean;
	readonly aspect_ratio: string;
	readonly thumbnail: string;
	readonly brand: Brand;
}
export interface Brand {
	readonly logo: string;
	readonly color: string;
	readonly link: string;
}
export interface Generic {
	readonly autoplay: boolean;
	readonly muted: boolean;
	readonly controls: boolean;
	readonly loop: boolean;
	readonly playback_rates: number[];
	readonly analytics: Analytics;
	readonly chromecast: Chromecast;
}
export interface Analytics {
	readonly google: string;
}
export interface Chromecast {
	readonly enabled: boolean;
	readonly receiver_application_id: string;
}
export interface Track {
	readonly id: number;
	readonly title: null;
	readonly full_title: string;
	readonly pluralized_title: string;
	readonly main: boolean;
	readonly sources: Sources;
	readonly qualities: Quality[];
}
export interface Sources {
	readonly hls: Dash;
	readonly dash: Dash;
	readonly mp4: null;
}
export interface Dash {
	readonly src: string;
	readonly type: string;
	readonly labels: string[];
	readonly labels_bitrate: LabelsBitrate;
}
export interface LabelsBitrate {
	readonly "1645": string;
}
export interface Quality {
	readonly label: string;
	readonly bitrate: number;
	readonly framerate: number;
}
export interface Advertising {
	readonly time: number;
	readonly tag: string;
	readonly nugg: boolean;
	readonly played: boolean;
}
