/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type VideoPlayer = VideoPlayerResponse;

export interface VideoPlayerResponse {
  options: Options;
  advertising: Advertising[];
  success: boolean;
}
export interface Options {
  visual: Visual;
  generic: Generic;
  tracks: Track[];
}
export interface Visual {
  fluid: boolean;
  responsive: boolean;
  aspect_ratio: string;
  thumbnail: string;
  brand: Brand;
}
export interface Brand {
  logo: string;
  color: string;
  link: string;
}
export interface Generic {
  autoplay: boolean;
  muted: boolean;
  controls: boolean;
  loop: boolean;
  playback_rates: number[];
  analytics: Analytics;
  chromecast: Chromecast;
}
export interface Analytics {
  google: string;
}
export interface Chromecast {
  enabled: boolean;
  receiver_application_id: string;
}
export interface Track {
  id: number;
  title: null;
  full_title: string;
  pluralized_title: string;
  main: boolean;
  sources: Sources;
  qualities: Quality[];
}
export interface Sources {
  hls: Dash;
  dash: Dash;
  mp4: null;
}
export interface Dash {
  src: string;
  type: string;
  labels: string[];
  labels_bitrate: LabelsBitrate;
}
export interface LabelsBitrate {
  "1645": string;
}
export interface Quality {
  label: string;
  bitrate: number;
  framerate: number;
}
export interface Advertising {
  time: number;
  tag: string;
  nugg: boolean;
  played: boolean;
}
